name: settings_yaml
version: 3.3.1
homepage: https://github.com/bsutton/settings_yaml
description: Provides a simple means of saving/loading settings from a yaml file without the yaml fuss.
environment: 
  sdk: '>=2.12.0 <3.0.0'
dependencies: 
  meta: ^1.3.0
  yaml: ^3.0.0
  path: ^1.8.0
  uuid: ^3.0.0
  collection: ^1.15.0
dev_dependencies: 
  test: ^1.16.2
  lints: ^1.0.0
  dcli: ^1.10.0
