name: settings_yaml
version: 6.0.0
homepage: https://github.com/bsutton/settings_yaml
description: Provides a simple means of saving/loading settings from a yaml file without the yaml fuss.
environment: 
  sdk: '>=2.19.0 <4.0.0'
dependencies: 
  collection: ^1.15.0
  dcli_core: ^2.2.0
  meta: ^1.3.0
  path: ^1.8.0
  uuid: ^3.0.0
  yaml: ^3.0.0
dev_dependencies: 
  lint_hard: ^3.0.1
  test: ^1.16.2
